'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { z } from 'zod';
import { createClient } from '@/lib/supabase/server';

const ExpiryChoice = z.enum(['none', '7_days', '30_days']);

const CreateShareSchema = z.object({
  recipientLabel: z.string().max(80),
  expiryChoice: ExpiryChoice,
});

export async function createShare(formData: FormData): Promise<void> {
  const parsed = CreateShareSchema.safeParse({
    recipientLabel: formData.get('recipient_label')?.toString().trim() ?? '',
    expiryChoice: formData.get('expiry_choice'),
  });
  if (!parsed.success) redirect('/family?error=invalid');

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect('/login');

  const { data: patient } = await supabase
    .from('patients')
    .select('id')
    .eq('caregiver_id', user.id)
    .order('created_at', { ascending: true })
    .limit(1)
    .single();
  if (!patient) redirect('/onboarding');

  // share_token is auto-generated by the schema default
  // (encode(gen_random_bytes(32),'hex')) — we do NOT supply it.
  const expiresAt = expiryDate(parsed.data.expiryChoice);
  const { error } = await supabase.from('family_shares').insert({
    patient_id: patient.id,
    recipient_label: parsed.data.recipientLabel || null,
    expires_at: expiresAt,
  });
  if (error) redirect('/family?error=save');

  revalidatePath('/family');
  redirect('/family');
}

function expiryDate(choice: 'none' | '7_days' | '30_days'): string | null {
  if (choice === 'none') return null;
  const days = choice === '7_days' ? 7 : 30;
  const ms = Date.now() + days * 24 * 60 * 60 * 1000;
  return new Date(ms).toISOString();
}

const RevokeSchema = z.object({
  shareId: z.string().uuid(),
});

export async function revokeShare(input: { shareId: string }): Promise<{
  ok?: boolean;
  error?: string;
}> {
  const parsed = RevokeSchema.safeParse(input);
  if (!parsed.success) return { error: 'Could not revoke that share.' };

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: 'Sign in again.' };

  const { error } = await supabase
    .from('family_shares')
    .update({ revoked_at: new Date().toISOString() })
    .eq('id', parsed.data.shareId);
  if (error) return { error: 'Could not revoke that share.' };

  revalidatePath('/family');
  return { ok: true };
}
